### ISSUE TITLE
crush_cookie bug?

### ISSUE THREAD

**Issue by nfg** [gonzus/http-xscookies#5]
Hello! I have a unit test that randomly breaks, and I tracked it down to crush_cookie. Here's a test case:

````perl
my $cookie = "product_data=blah; Expires=Mon, 30-Oct-2017 19:02:53 GMT; Path=/; HttpOnly";
say Dumper(crush_cookie($cookie));
# { product_data => "blah", Expires => "Mon, 30-Oct-2017 19:02:53 GMT", "Path" => 1 }

$cookie = "product_data=blah; HttpOnly; Expires=Mon, 30-Oct-2017 19:02:53 GMT";
say Dumper(crush_cookie($cookie));
# { product_data => "blah" } 
````

So basically, when the parser reads HttpOnly, it errors out. If I read the RFC correctly, that should be a valid Set-Cookie header.

**Comment by gonzus** [comment]
Holy crap, I totally forgot that I had seen these emails from you. I want to apologize first. I will take a look at your issues now.

**Comment by nfg** [comment]
No worries! For what it's worth, I also created a pull request (#6) with a possible fix. Cheers. :)

**Comment by gonzus** [comment]
I fixed it with what I think is a cleaner way. Also added tests, which now pass. Thanks for your report; I will publish a new release soon.

**Comment by gonzus** [comment]
Uploaded HTTP-XSCookies-0.000016.tar.gz to CPAN. Cheers!

**Comment by nfg** [comment]
Cool! Thanks for fixing this. :)

**Comment by whosgonna** [comment]
FYI, it looks like this change breaks some expected behavior in Dancer2.  I've opened [an issue](https://github.com/PerlDancer/Dancer2/issues/1435) there, but it does look like you [worked with them](https://github.com/PerlDancer/Dancer2/issues/1087) to some degree on this before.   As I note in the Dancer2 issue, the ```crush_cookie``` method does indicate that it is intended to parse "properly encoded" cookies,  though.

**Comment by gonzus** [comment]
Oops. Commented in that Dancer2 issue, let's see where this goes.
